//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

namespace IsoXml.XML
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class ISO11783_TaskData
    {
        private ISO11783_TaskDataDVC[] dVCField;    

        private ISO11783_TaskDataXFR[] xFRField;    

        private ISO11783_TaskDataTSK[] tSKField;

        private ISO11783_TaskDataPDT[] pDTField;

        private string versionMajorField;

        private string versionMinorField;

        private string managementSoftwareManufacturerField;

        private string managementSoftwareVersionField;

        private string dataTransferOriginField;


        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DVC", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ISO11783_TaskDataDVC[] DVC
        {
            get
            {
                return this.dVCField;
            }
            set
            {
                this.dVCField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("XFR", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ISO11783_TaskDataXFR[] XFR
        {
            get
            {
                return this.xFRField;
            }
            set
            {
                this.xFRField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TSK", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ISO11783_TaskDataTSK[] TSK
        {
            get
            {
                return this.tSKField;
            }
            set
            {
                this.tSKField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PDT", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ISO11783_TaskDataPDT[] PDT
        {
            get
            {
                return this.pDTField;
            }
            set
            {
                this.pDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VersionMajor
        {
            get
            {
                return this.versionMajorField;
            }
            set
            {
                this.versionMajorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string VersionMinor
        {
            get
            {
                return this.versionMinorField;
            }
            set
            {
                this.versionMinorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ManagementSoftwareManufacturer
        {
            get
            {
                return this.managementSoftwareManufacturerField;
            }
            set
            {
                this.managementSoftwareManufacturerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ManagementSoftwareVersion
        {
            get
            {
                return this.managementSoftwareVersionField;
            }
            set
            {
                this.managementSoftwareVersionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DataTransferOrigin
        {
            get
            {
                return this.dataTransferOriginField;
            }
            set
            {
                this.dataTransferOriginField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ISO11783_TaskDataXFR
    {

        private string aField;

        private string bField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A
        {
            get
            {
                return this.aField;
            }
            set
            {
                this.aField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string B
        {
            get
            {
                return this.bField;
            }
            set
            {
                this.bField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class NewDataSet
    {

        private ISO11783_TaskData[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ISO11783_TaskData")]
        public ISO11783_TaskData[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }



    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ISO11783_TaskDataDPD
    {

        private string aField;

        private string bField;

        private string cField;

        private string dField;

        private string eField;

        private int fField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A
        {
            get
            {
                return this.aField;
            }
            set
            {
                this.aField = value;
            }
        }

        /// <summary>
        /// Unique number which specifies the process data variable
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string B
        {
            get
            {
                return this.bField;
            }
            set
            {
                this.bField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string C
        {
            get
            {
                return this.cField;
            }
            set
            {
                this.cField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string D
        {
            get
            {
                return this.dField;
            }
            set
            {
                this.dField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E
        {
            get
            {
                return this.eField;
            }
            set
            {
                this.eField = value;
            }
        }

        /// <summary>
        /// Object ID of DeviceValuePresentation
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int F
        {
            get
            {
                return this.fField;
            }
            set
            {
                this.fField = value;
            }
        }
    }




    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ISO11783_TaskDataDET
    {

        private string aField;

        private string bField;

        private string cField;

        private string dField;

        private string eField;

        private string fField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A
        {
            get
            {
                return this.aField;
            }
            set
            {
                this.aField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string B
        {
            get
            {
                return this.bField;
            }
            set
            {
                this.bField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string C
        {
            get
            {
                return this.cField;
            }
            set
            {
                this.cField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string D
        {
            get
            {
                return this.dField;
            }
            set
            {
                this.dField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E
        {
            get
            {
                return this.eField;
            }
            set
            {
                this.eField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F
        {
            get
            {
                return this.fField;
            }
            set
            {
                this.fField = value;
            }
        }

        /// <remarks/>
        public ISO11783_TaskDataDOR DOR;
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ISO11783_TaskDataDOR
    {

        private string aField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A
        {
            get
            {
                return this.aField;
            }
            set
            {
                this.aField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ISO11783_TaskDataPAN
    {

        private string aField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A
        {
            get
            {
                return this.aField;
            }
            set
            {
                this.aField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ISO11783_TaskDataTSK
    {
        private string aField;

        private string bField;

        private string cField;

        private string dField;

        private string eField;

        private string gField;

        private ISO11783_TaskDataPAN pANField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PAN", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ISO11783_TaskDataPAN PAN
        {
            get
            {
                return this.pANField;
            }
            set
            {
                this.pANField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A
        {
            get
            {
                return this.aField;
            }
            set
            {
                this.aField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string B
        {
            get
            {
                return this.bField;
            }
            set
            {
                this.bField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string C
        {
            get
            {
                return this.cField;
            }
            set
            {
                this.cField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string D
        {
            get
            {
                return this.dField;
            }
            set
            {
                this.dField = value;
            }
        }

        /// <summary>
        /// Reference to XML element Partfield Format: (PFD|PFD-)([0-9])+
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E
        {
            get
            {
                return this.eField;
            }
            set
            {
                this.eField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string G
        {
            get
            {
                return this.gField;
            }
            set
            {
                this.gField = value;
            }
        }

        public ISO11783_TaskDataTLG TLG;
        public ISO11783_TaskDataGRD GRD;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TZN")]
        public ISO11783_TaskDataTSKTZN[] TZN;
    }




    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ISO11783_TaskDataTLG
    {

        private string aField;

        private string cField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A
        {
            get
            {
                return this.aField;
            }
            set
            {
                this.aField = value;
            }
        }        

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string C
        {
            get
            {
                return this.cField;
            }
            set
            {
                this.cField = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ISO11783_TaskDataGRD
    {

        private double aField;

        private double bField;

        private double cField;

        private double dField;

        private int eField;

        private int fField;

        private string gField;

        private string hField;

        private int iField;

        private string jField;

        /// <summary>
        /// MinimumNorth
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double A
        {
            get
            {
                return this.aField;
            }
            set
            {
                this.aField = value;
            }
        }

        /// <summary>
        /// MinimumEast
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double B
        {
            get
            {
                return this.bField;
            }
            set
            {
                this.bField = value;
            }
        }

        /// <summary>
        /// GridCellNorthSize
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double C
        {
            get
            {
                return this.cField;
            }
            set
            {
                this.cField = value;
            }
        }

        /// <summary>
        /// GridCellEastSize
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double D
        {
            get
            {
                return this.dField;
            }
            set
            {
                this.dField = value;
            }
        }

        /// <summary>
        /// GridMaximumColumn
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int E
        {
            get
            {
                return this.eField;
            }
            set
            {
                this.eField = value;
            }
        }

        /// <summary>
        /// GridMaximumRow
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int F
        {
            get
            {
                return this.fField;
            }
            set
            {
                this.fField = value;
            }
        }

        /// <summary>
        /// Filename
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string G
        {
            get
            {
                return this.gField;
            }
            set
            {
                this.gField = value;
            }
        }

        /// <summary>
        /// Filelength
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string H
        {
            get
            {
                return this.hField;
            }
            set
            {
                this.hField = value;
            }
        }

        /// <summary>
        /// GridType
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int I
        {
            get
            {
                return this.iField;
            }
            set
            {
                this.iField = value;
            }
        }

        /// <summary>
        /// TreatmentZoneCode
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string J
        {
            get
            {
                return this.jField;
            }
            set
            {
                this.jField = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ISO11783_TaskDataTSKTZN
    {

        private PDV[] pDVField;

        private int aField;

        private string bField;

        private string cField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PDV")]
        public PDV[] PDV
        {
            get
            {
                return this.pDVField;
            }
            set
            {
                this.pDVField = value;
            }
        }

        /// <summary>
        /// Unique TreatmentZoneCode inside a task
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int A
        {
            get
            {
                return this.aField;
            }
            set
            {
                this.aField = value;
            }
        }

        /// <summary>
        /// Name of TreatmentZone
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string B
        {
            get
            {
                return this.bField;
            }
            set
            {
                this.bField = value;
            }
        }

        /// <summary>
        /// Colour of TreatmentZone
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string C
        {
            get
            {
                return this.cField;
            }
            set
            {
                this.cField = value;
            }
        }

    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class PDV
    {

        private PDV[] pDV1Field;

        private string aField;

        private long bField;

        private string cField;

        private string eField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PDV")]
        public PDV[] PDV1
        {
            get
            {
                return this.pDV1Field;
            }
            set
            {
                this.pDV1Field = value;
            }
        }

        /// <summary>
        /// Unique number which defines the process data DDI (specified in ISO 11783-11)
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A
        {
            get
            {
                return this.aField;
            }
            set
            {
                this.aField = value;
            }
        }

        /// <summary>
        /// Contains the value of the process data DDI
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long B
        {
            get
            {
                return this.bField;
            }
            set
            {
                this.bField = value;
            }
        }

        /// <summary>
        /// Reference to XML element Product Format: (PDT|PDT-)([0-9])
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string C
        {
            get
            {
                return this.cField;
            }
            set
            {
                this.cField = value;
            }
        }

        /// <summary>
        /// Reference to XML element ValuePresentation Format: (VPN|VPN-)([0-9])
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E
        {
            get
            {
                return this.eField;
            }
            set
            {
                this.eField = value;
            }
        }
    }



    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ISO11783_TaskDataVPN
    {

        private string aField;

        private string bField;

        private double cField;

        private string dField;

        private string eField;

        /// <summary>
        /// Id
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A
        {
            get
            {
                return this.aField;
            }
            set
            {
                this.aField = value;
            }
        }

        /// <summary>
        /// Offset to be applied to the value for presentation
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string B
        {
            get
            {
                return this.bField;
            }
            set
            {
                this.bField = value;
            }
        }

        /// <summary>
        /// Scale to be applied to the value for presentation
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double C
        {
            get
            {
                return this.cField;
            }
            set
            {
                this.cField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string D
        {
            get
            {
                return this.dField;
            }
            set
            {
                this.dField = value;
            }
        }

        /// <summary>
        /// Unit Designator
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E
        {
            get
            {
                return this.eField;
            }
            set
            {
                this.eField = value;
            }
        }
    }



    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ISO11783_TaskDataPDT
    {

        private string aField;

        private string bField;

        private string cField;

        private string dField;

        /// <summary>
        /// Product Id
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A
        {
            get
            {
                return this.aField;
            }
            set
            {
                this.aField = value;
            }
        }

        /// <summary>
        /// Product designator/name
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string B
        {
            get
            {
                return this.bField;
            }
            set
            {
                this.bField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string C
        {
            get
            {
                return this.cField;
            }
            set
            {
                this.cField = value;
            }
        }

        /// <summary>
        /// ValuePresentationIdRef
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string D
        {
            get
            {
                return this.dField;
            }
            set
            {
                this.dField = value;
            }
        }
    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ISO11783_TaskDataDVP
    {

        private int aField;

        private long bField;

        private double cField;

        private byte dField;

        private string eField;

        /// <summary>
        /// Unique number inside a single device
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int A
        {
            get
            {
                return this.aField;
            }
            set
            {
                this.aField = value;
            }
        }

        /// <summary>
        /// Offset to be applied to the value for presentation
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long B
        {
            get
            {
                return this.bField;
            }
            set
            {
                this.bField = value;
            }
        }

        /// <summary>
        /// Scale to be applied to the value for presentation
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public double C
        {
            get
            {
                return this.cField;
            }
            set
            {
                this.cField = value;
            }
        }

        /// <summary>
        /// Number of decimals to be presented after the decimal separator
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte D
        {
            get
            {
                return this.dField;
            }
            set
            {
                this.dField = value;
            }
        }

        /// <summary>
        /// Optional unit designator string
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string E
        {
            get
            {
                return this.eField;
            }
            set
            {
                this.eField = value;
            }
        }
    }



    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ISO11783_TaskDataDVC
    {

        private string aField;

        private string bField;

        private string cField;

        private string dField;

        private string fField;

        private string gField;

        private ISO11783_TaskDataDET[] dETField;

        private ISO11783_TaskDataDPD[] dPDField;

        private ISO11783_TaskDataDVP[] dVPField;

        /// <summary>
        /// Unique identifier of device Format: (DVC|DVC-)([0-9])+
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string A
        {
            get
            {
                return this.aField;
            }
            set
            {
                this.aField = value;
            }
        }

        /// <summary>
        /// Device designator
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string B
        {
            get
            {
                return this.bField;
            }
            set
            {
                this.bField = value;
            }
        }

        /// <summary>
        /// Software version of device
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string C
        {
            get
            {
                return this.cField;
            }
            set
            {
                this.cField = value;
            }
        }

        /// <summary>
        /// xs:hexBinary 0x0000000000000000 .. 0xFFFFFFFFFFFFFFFF NAME of working-set master (see ISO 11783-5)
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string D
        {
            get
            {
                return this.dField;
            }
            set
            {
                this.dField = value;
            }
        }

        /// <summary>
        /// xs:hexBinary 0x00 .. 0xFE per byte
        /// Label of device description structure
        /// Array Byte 1 is most significant and
        /// Array Byte 7 is least significant.
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F
        {
            get
            {
                return this.fField;
            }
            set
            {
                this.fField = value;
            }
        }

        /// <summary>
        /// xs:hexBinary
        /// Bytes 1 to 6: 0x00 ..
        /// 0xFE per byte,
        /// Byte 7 = 0xFF
        /// Label of device description
        /// localization.
        /// Bytes 1 to 6 are defined by the
        /// language command PGN (see
        /// ISO 11783-7). Byte 7 is reserved and
        /// set to FF16. Language command
        /// PGN Byte 1 is least significant and
        /// language command Byte 7 is most
        /// significant.
        /// </summary>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string G
        {
            get
            {
                return this.gField;
            }
            set
            {
                this.gField = value;
            }
        }


        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DET", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ISO11783_TaskDataDET[] DET
        {
            get
            {
                return this.dETField;
            }
            set
            {
                this.dETField = value;
            }
        }


        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DPD", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ISO11783_TaskDataDPD[] DPD
        {
            get
            {
                return this.dPDField;
            }
            set
            {
                this.dPDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DVP", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ISO11783_TaskDataDVP[] DVP
        {
            get
            {
                return this.dVPField;
            }
            set
            {
                this.dVPField = value;
            }
        }
    }
}